plot3 <- function(directory=getwd()){
  library(dplyr)
  library(lubridate)
  setwd(directory)
  df <- read.table("household_power_consumption.txt",sep=";",na.strings = "?",header=TRUE)
  df <- subset(df, Date=="2/2/2007"|Date=="1/2/2007")
  df <- mutate(df,DateTime=dmy_hms(paste(Date,Time,sep=" ")))
  png("plot3.png")
  with(df,plot(DateTime,Sub_metering_1,type="n",ylab="Energy sub metering",xlab=" "))
  lines(df$DateTime,df$Sub_metering_1)
  lines(df$DateTime,df$Sub_metering_2,col="red")
  lines(df$DateTime,df$Sub_metering_3,col="blue")
  legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=1,col=c("black","red","blue"))
  dev.off()
}